
services:
  web:
    image: sougatamaity/dicom-modification:v1
    container_name: kms_dcm_modification
    ports:
      - "8099:8501"
    volumes: 
      - kms_dcm_modification:/app
    env_file:
      - .env
 
    restart: always

volumes:
  kms_dcm_modification:
